import type { Metadata } from 'next';

import '@/app/styles/globals.css';

import styles from '@/app/styles/components/page.module.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function PostLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <div className={`${styles['simple-page-layout']}`}>
      {children}
    </div>
  )
}
