import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/styles/globals.css';

import { getDictionary } from '@/lib/localization';
import { getUser } from '@/lib/profile-controller';

import Footer from '@/components/common/Footer';
import Header from '@/components/common/Header';
import FixedRoundCreatePostButton from '@/components/buttons/FixedRoundCreatePostButton';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const user = getUser();
  const dict = await getDictionary('en');

  return (
    <html lang="en" className='size-full'>
      <body className={`${inter.className} size-full flex flex-col items-stretch relative`}>
        <Header local={dict} />
        <main className='flex flex-grow relative flex-shrink-0 bg-slate-600'>
          {children}
          <FixedRoundCreatePostButton />
        </main>
        <Footer local={dict} />
      </body>
    </html>
  )
}
