import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/styles/globals.css';

import { getDictionary } from '@/lib/localization';

import Footer from '@/components/common/Footer';
import Header from '@/components/common/Header';
import FixedRoundCreatePostButton from '@/components/buttons/FixedRoundCreatePostButton';
import AuthProvider from '@/components/common/AuthProvider';
import { getCurrentUser } from '@/actions/actions';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const dict = await getDictionary('en');
  const user: UserDTO | undefined = await getCurrentUser();

  return (
    <html lang="en" className='size-full'>
      <AuthProvider>
        <body className={`${inter.className} size-full flex flex-col items-stretch relative`}>
          <Header local={dict} user={user} />
          <main className='flex flex-grow relative flex-shrink-0 bg-gray-50 mt-20'>
            {children}
            {user &&
              <FixedRoundCreatePostButton />
            }
          </main>
          <Footer local={dict} />
        </body>
      </AuthProvider>
    </html>
  )
}
