import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import '@/app/styles/globals.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <div className='flex flex-grow flex-col w-full relative flex-shrink-0'>
      <div className="flex flex-auto justify-center w-full">
        <div className='flex w-full max-w-6xl bg-white m-4 p-4 rounded-2xl'>
          <section className="flex flex-col flex-grow flex-shrink-0 p-2 md:p-4 items-center">
            {children}
          </section>
        </div>
      </div>
    </div>
  )
}
