services:
  frontend-api:
    container_name: frontend-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - external_network
      
networks:
  external_network:
    name: microservice_network
    external: true
